apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    securityContext:
      privileged: true
      runAsUser: 0
    image: docker.io/ubuntu
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
